Include CPU walltime for control case

diff --git a/bin/diag_srun b/bin/diag_srun
--- a/bin/diag_srun
+++ b/bin/diag_srun
@@ -6,7 +6,7 @@ DIAG_PATH="/cluster/work/users/$USER/diagnostics/out"
 LOG_PATH="/cluster/work/users/$USER/diagnostics/logs"
 
 if [ $# -eq 0 ] || [ $1 == "-h" ]; then
-    echo ""
+    echo " "
     echo "Short description:"
     echo "A wrapper script for submitting a preproc job on Betzy for the NorESM diagnostic packages."
     echo " "
@@ -14,24 +14,24 @@ if [ $# -eq 0 ] || [ $1 == "-h" ]; then
     echo "  --account=nsxxxxk                             Project account for CPU hours (OPTIONAL, default ns2345k)."
     echo "  --time=DD-HH:MM:SS                            CPU walltime (OPTIONAL, default value according to length of years and active components)."
     echo "  --remove-source-files-flag=true|false         Flag if the source file will be removed after the webpage is moved from Betzy /cluster to NIRD /project* (OPTIONAL, default as false)."
-    echo ""
+    echo " "
     echo "Examples:"
-    echo ""
-    echo "1, Use default settings"
+    echo " "
+    echo "1. Use default settings"
     echo "\$ ./diag_srun -m blom -c test_case_name -s 1 -e 10"
-    echo ""
-    echo "2, Set CPU account and hours"
+    echo " "
+    echo "2. Set CPU account and hours"
     echo "\$ ./diag_srun -m blom -c test_case_name -s 1 -e 10 --account=nn2345k --time=0-00:59:00"
-    echo ""
-    echo "3, Set input data, output data, and webpage path to /cluster on Betzy (the same as default values)"
+    echo " "
+    echo "3. Set input data, output data, and webpage path to /cluster on Betzy (the same as default values)"
     echo "\$ ./diag_srun -m blom -c NOICPLHISTOC_f09_tn14_cpldiags -s 1 -e 20 -i /cluster/work/users/$USER/archive -o /cluster/work/users/$USER/diagnostics/out -w /cluster/work/users/$USER/diagnostics/web"
-    echo ""
-    echo "4, Set input data, output data on Betzy, and webpage path on NIRD"
+    echo " "
+    echo "4. Set input data, output data on Betzy, and webpage path on NIRD"
     echo "\$ ./diag_srun -m blom -c NOICPLHISTOC_f09_tn14_cpldiags -s 1 -e 20 -w /trd-project1/NS2345K/www/diagnostics/noresm/$USER/ --account=nn2345k --time=0-00:59:00"
-    echo ""
-    echo "5, Remove source webpage files from Betzy after transferred to NIRD"
+    echo " "
+    echo "5. Remove source webpage files from Betzy after transferred to NIRD"
     echo "\$ ./diag_srun -m blom -c NOICPLHISTOC_f09_tn14_cpldiags -s 1 -e 20 -w /trd-project1/NS2345K/www/diagnostics/noresm/$USER/ --remove-source-files-flag=true"
-    echo ""
+    echo " "
     echo "See more help:"
     echo "/cluster/shared/noresm/diagnostics/noresm/bin/diag_run -h "
     echo " ** EXIT THE SCRIPT **"
@@ -76,6 +76,21 @@ while test $# -gt 0; do
             SYR1=`echo $1 | sed -e 's/^[^=]*=//g'`
             shift
             ;;
+        -s2)
+            shift
+            if test $# -gt 0; then
+                SYR2=$1
+            else
+                echo "ERROR: no start yr of cntl case specified (-s2, --start_yr2)"
+                echo "*** EXITING THE SCRIPT"
+                exit 1
+            fi
+            shift
+            ;;
+        --start_yr2=*)
+            SYR2=`echo $1 | sed -e 's/^[^=]*=//g'`
+            shift
+            ;;
         -e | -e1)
             shift
             if test $# -gt 0; then
@@ -91,7 +106,21 @@ while test $# -gt 0; do
             EYR1=`echo $1 | sed -e 's/^[^=]*=//g'`
             shift
             ;;
-
+        -e2)
+            shift
+            if test $# -gt 0; then
+                EYR2=$1
+            else
+                echo "ERROR: no end yr of cntl case specified (-e2, --end_yr2)"
+                echo "*** EXITING THE SCRIPT"
+                exit 1
+            fi
+            shift
+            ;;
+        --end_yr2=*)
+            EYR2=`echo $1 | sed -e 's/^[^=]*=//g'`
+            shift
+            ;;
         -m)
             shift
             if test $# -gt 0; then
@@ -207,6 +236,10 @@ else
     done
 fi
 N10Y=$(echo "if (($EYR1-$SYR1+1)%10) ($EYR1-$SYR1+1)/10+1 else ($EYR1-$SYR1+1)/10 " |bc)
+if [ ! -z $SYR2 ] && [ ! -z $EYR2 ];then
+    N10Y2=$(echo "if (($EYR2-$SYR2+1)%10) ($EYR2-$SYR2+1)/10+1 else ($EYR2-$SYR2+1)/10 " |bc)
+    N10Y=$(($N10Y+$N10Y2))
+fi
 WTT=$(($WTT*$N10Y))
 DD=$(($WTT/24/60))
 HH=$((($WTT-$DD*24*60)/60))
@@ -222,41 +255,41 @@ if [ ! $(echo $DIAG_PATH |grep '\/cluster\/') ]; then
     exit 1
 fi
 if [ $(echo $WEB_PATH |grep -P '\/trd-project\d\/') ]; then
-    echo "          "
+    echo " "
     echo "**  **  **"
     echo "WARNING: WEB_PATH is set to nird: $WEB_PATH"
     WEB_PATH0=$WEB_PATH
     WEB_PATH=/cluster/work/users/$USER/diagnostics/www
-    echo "WEB_PATH is temporary set to $WEB_PATH, which is only reachable from the compute nodes."
-    echo "The created webpage will be moved to $WEB_PATH0/$CASE1 after the diagnostic is done."
+    echo "WEB_PATH is now temporarily set to the path below, which is only reachable from the compute nodes."
+    echo "$WEB_PATH."
+    echo "The created webpage will be moved to the path below, after the diagnostic is done."
+    echo "$WEB_PATH0/$CASE1"
     echo "**  **  **"
-    echo "          "
+    echo " "
 fi
 if [ -z $ACCOUNT ]; then
-    echo "          "
     echo "**  **  **"
     echo "WARNING: CPU acount is not specificed"
     echo "Set default to #SBATCH --account=nn2345k"
     echo "**  **  **"
-    echo "          "
+    echo " "
     ACCOUNT='nn2345k'
 fi
 if [ -z $TIME ]; then
     TIME=$(getwt)
-    echo "          "
     echo "**  **  **"
     echo "WARNING: CPU hours is not specificed"
     echo "Set default to #SBATCH --time=$TIME"
     echo "**  **  **"
-    echo "          "
+    echo " "
 fi
 
 ## Remove and restore arguments passing to diag_run
 ARG=$(echo $ARG |sed 's/--time=\S*//g' |sed 's/--account=\S*//g')
 [ ! -z $WEB_PATH0 ] && ARG=$(echo $ARG |sed "s% *-w \S.* *% -w $WEB_PATH %" |sed "s% *--web-dir=\S.* *% --web-dir=$WEB_PATH %")
                                                                              #sed "s% *--web-dir=\S.* *% --web-dir=$WEB_PATH %"
-#dateYYYYMMDD=$(date +%y%m%d)
-#dateHHMMSS=$(date +%H%M%S)
+YMD=$(date +%y%m%d)
+HMS=$(date +%H%M%S)
 
 ## SBATCH job
 cat <<EOF >/tmp/submit$$.sh
@@ -264,13 +297,12 @@ cat <<EOF >/tmp/submit$$.sh
 # Script template to submit a diagnostic job on Betzy #
 
 #SBATCH --account=$ACCOUNT
-#SBATCH --job-name=diag_srun-$CASE1
+#SBATCH --job-name=diagsrun-$CASE1
 #SBATCH --partition=preproc
 #SBATCH --ntasks=1 --cpus-per-task=12
 #SBATCH --mem-per-cpu=2G
 #SBATCH --time=$TIME
-#SBATCH --output=${LOG_PATH}/slurm-$$.log
-#SBATCH --output=${LOG_PATH}/slurm-$$.log
+#SBATCH --output=${LOG_PATH}/slurm-${YMD}-${HMS}.log
 #SBATCH --parsable 
 
 ## safety settings:
@@ -282,7 +314,7 @@ set -o nounset
 cd /cluster/shared/noresm/diagnostics/noresm/bin
 
 ## Run job
-srun --output=${LOG_PATH}/diag_srun-$$.log ./diag_run $ARG
+srun --output=${LOG_PATH}/diagsrun-${YMD}-${HMS}.log ./diag_run $ARG
 
 exit 0
 
@@ -295,11 +327,11 @@ rm -f /tmp/submit$$.sh
 
 # Log files
 echo "Check the log of SBATCH job status:"
-echo "${LOG_PATH}/slurm-$$.log"
-echo "                       "
-echo "Check the log of diag_run:"
-echo "${LOG_PATH}/diag_srun-$$.log"
-echo "                       "
+echo "${LOG_PATH}/slurm-${YMD}-${HMS}.log"
+echo " "
+echo "Check the log of diag_srun:"
+echo "${LOG_PATH}/diagsrun-${YMD}-${HMS}.log"
+echo " "
 
 # Copy output from cluster to NIRD after job finishes, if required
 while [ $(squeue -j $jobid 2>/dev/null |wc -l) -eq 2 ];do
@@ -307,21 +339,24 @@ while [ $(squeue -j $jobid 2>/dev/null |wc -l) -eq 2 ];do
 done
 
 if [ $(echo $WEB_PATH0 |grep -P '\/trd-project\d\/') ]; then
-    echo "Moving the created webpage to NIRD: $WEB_PATH0/$CASE1"
+    echo "The created webpage will be moved to NIRD: "
+    echo "$WEB_PATH0/$CASE1"
+    echo "Check the rsync log:"
+    echo "${LOG_PATH}/rsync-${YMD}-${HMS}.log "
+    echo " "
     if $REMOVE_SOURCE_FILES_FLAG; then
-        echo "And remove source files and clean up empty folders."
-        echo "** BE CAUTIOUS WITH THE RISK ** "
-        echo "Check the log: ${LOG_PATH}/rsync-$$.log "
-        rsync -vazu --remove-source-files $WEB_PATH/$CASE1/ $WEB_PATH0/$CASE1/ &>${LOG_PATH}/rsync-$$.log &
+        #echo "(NB, the source files: $WEB_PATH/$CASE1)"
+        #echo "(will be removed after they are synchronized)"
+        #echo "(** BE CAUTIOUS WITH THE RISK ** )"
+        rsync -vazu --remove-source-files $WEB_PATH/$CASE1/ $WEB_PATH0/$CASE1/ &>${LOG_PATH}/rsync-${YMD}-${HMS}.log &
         wait
         tmpdir=$(mktemp -d)
-        rsync -av --delete $tmpdir/ $WEB_PATH/$CASE1/ &>>${LOG_PATH}/rsync-$$.log &
+        rsync -av --delete $tmpdir/ $WEB_PATH/$CASE1/ &>>${LOG_PATH}/rsync-${YMD}-${HMS}.log &
         wait && rmdir $tmpdir
          #**                           **
     else
-        echo "Check the log: ${LOG_PATH}/rsync-$$.log "
-        echo "                                     "
-        rsync -vazu $WEB_PATH/$CASE1/ $WEB_PATH0/$CASE1/ &>${LOG_PATH}/rsync-$$.log &
+        echo " "
+        rsync -vazu $WEB_PATH/$CASE1/ $WEB_PATH0/$CASE1/ &>${LOG_PATH}/rsync-${YMD}-${HMS}.log &
         wait
     fi
 
